services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - MOCK_LLM_API_URL=http://mock-llm:8080
    ports:
      - "3000:3000"
    depends_on:
      - mock-llm
    restart: unless-stopped

  mock-llm:
    build:
      context: ./mock-llm
      dockerfile: Dockerfile
    restart: unless-stopped
